spring:
  datasource:
    url: jdbc:mysql://rm-wz9s7ffvere4dy5zdfo.mysql.rds.aliyuncs.com:3306/elasticsearch?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Wzx123456
    #druid连接池配置
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"  #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

      #下面这两个配置，可以在每次连接的时候判断一些连接是否有效
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

#服务启动端口好
server:
  port: 8899

#日志
logging:
  level:
    root: info
    com.wuzx.fun.study_elasticsearch: debug


#Mybastis配置
mybatis:
  type-aliases-package: com/wuzx/fun/study_elasticsearch/model
  mapper-locations: classpath:mapper/*Mapper.xml

elasticsearch:
  host: 120.78.81.89
  port: 9200